// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yseyzbufteogsnygvbzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZXl6YnVmdGVvZ3NueWd2YnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDQ0MTksImV4cCI6MjA2ODE4MDQxOX0.xjz2mC1bqTU5W4LhuFzjQVL0yVWvwj2fx0YZdv2xnq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});